from __future__ import annotations

from .models import EtfTarget


ETF_TARGETS = {
    "069500": EtfTarget(
        code="069500",
        name="KODEX 200",
        theme="market_beta",
        risk_bucket="core",
        max_weight_initial=0.20,
        max_weight_normal=0.30,
        min_stop_pct=0.0050,
        max_stop_pct=0.0090,
        max_slippage_pct=0.0006,
    ),
    "091160": EtfTarget(
        code="091160",
        name="KODEX Semiconductors",
        theme="semiconductor",
        risk_bucket="growth",
        max_weight_initial=0.20,
        max_weight_normal=0.28,
        min_stop_pct=0.0070,
        max_stop_pct=0.0120,
        max_slippage_pct=0.0010,
    ),
    "305720": EtfTarget(
        code="305720",
        name="KODEX Secondary Battery Industry",
        theme="battery",
        risk_bucket="growth",
        max_weight_initial=0.15,
        max_weight_normal=0.20,
        min_stop_pct=0.0080,
        max_stop_pct=0.0140,
        max_slippage_pct=0.0012,
        stricter=True,
    ),
    "117460": EtfTarget(
        code="117460",
        name="KODEX Energy Chemicals",
        theme="energy_chemicals",
        risk_bucket="cyclical",
        max_weight_initial=0.12,
        max_weight_normal=0.18,
        min_stop_pct=0.0080,
        max_stop_pct=0.0140,
        max_slippage_pct=0.0015,
        stricter=True,
    ),
    "463250": EtfTarget(
        code="463250",
        name="TIGER K-Defense & Space",
        theme="defense_space",
        risk_bucket="thematic",
        max_weight_initial=0.12,
        max_weight_normal=0.18,
        min_stop_pct=0.0080,
        max_stop_pct=0.0150,
        max_slippage_pct=0.0015,
        stricter=True,
    ),
    "466920": EtfTarget(
        code="466920",
        name="SOL Shipbuilding TOP3 Plus",
        theme="shipbuilding",
        risk_bucket="cyclical",
        max_weight_initial=0.12,
        max_weight_normal=0.18,
        min_stop_pct=0.0080,
        max_stop_pct=0.0150,
        max_slippage_pct=0.0015,
        stricter=True,
    ),
    "445290": EtfTarget(
        code="445290",
        name="KODEX Robot Active",
        theme="robotics",
        risk_bucket="growth",
        max_weight_initial=0.10,
        max_weight_normal=0.16,
        min_stop_pct=0.0090,
        max_stop_pct=0.0160,
        max_slippage_pct=0.0018,
        stricter=True,
    ),
    "433500": EtfTarget(
        code="433500",
        name="ACE Nuclear TOP10",
        theme="nuclear",
        risk_bucket="thematic",
        max_weight_initial=0.10,
        max_weight_normal=0.15,
        min_stop_pct=0.0100,
        max_stop_pct=0.0180,
        max_slippage_pct=0.0020,
        stricter=True,
    ),
    "364970": EtfTarget(
        code="364970",
        name="TIGER Bio TOP10",
        theme="bio",
        risk_bucket="defensive_growth",
        max_weight_initial=0.08,
        max_weight_normal=0.12,
        min_stop_pct=0.0120,
        max_stop_pct=0.0200,
        max_slippage_pct=0.0025,
        stricter=True,
    ),
    "471990": EtfTarget(
        code="471990",
        name="KODEX AI Semiconductor Equipment",
        theme="ai_semiconductor_equipment",
        risk_bucket="growth",
        max_weight_initial=0.10,
        max_weight_normal=0.16,
        min_stop_pct=0.0100,
        max_stop_pct=0.0180,
        max_slippage_pct=0.0020,
        stricter=True,
    ),
}


LEAD_INDICATORS = {
    "069500": ["KOSPI200_NIGHT", "EWY", "SPX", "NDX", "USDKRW", "VIX"],
    "091160": ["SOX", "SOXX", "SMH", "NVDA", "MU", "AMD", "TSM", "NDX"],
    "305720": ["TSLA", "LIT", "BATT", "ALB", "SQM", "NDX", "USDKRW"],
    "117460": ["XLE", "XOP", "OIH", "USO", "XOM", "CVX", "COP", "USDKRW"],
    "463250": ["ITA", "XAR", "PPA", "LMT", "RTX", "NOC", "RKLB", "ARKX", "BA", "NDX"],
    "466920": ["BOAT", "SEA", "LNG", "FLNG", "STNG", "CAT", "GE", "USDKRW"],
    "445290": ["BOTZ", "ROBO", "IRBO", "NVDA", "TSLA", "ISRG", "TER", "NDX"],
    "433500": ["URA", "URNM", "CCJ", "SMR", "UEC", "XLU", "USDKRW"],
    "364970": ["XBI", "IBB", "XLV", "MRNA", "REGN", "LLY", "NDX"],
    "471990": ["SOXX", "SMH", "NVDA", "AMD", "AVGO", "ASML", "AMAT", "LRCX", "SOX", "NDX"],
}
